project_id = "gfgyocmkhudhevbeyjss"

[functions.scrape-manga]
verify_jwt = false

[functions.scrape-catalog]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.auto-scraper]
verify_jwt = false
